<a href="https://colab.research.google.com/github/SujoyDaniel/GoogleCob/blob/GoogleCode/Sujoycode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the libraries Importing the Dataset

In [2]:
ds = pd.read_csv('Data.csv')
x = ds.iloc[:, :-1].values
y = ds.iloc[:, -1].values

In [3]:
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking save of Missing Values

In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.NaN, strategy='mean')
 
ds.Age = imputer.fit_transform(ds['Age'].values.reshape(-1,1))[:,0]
ds.Salary = imputer.fit_transform(ds['Salary'].values.reshape(-1,1))[:,0]
 
ds

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

Encoding the Independent Variable

In [5]:
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding the Dependent Variable

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting Dataset into TrainSet and TestSet

In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [8]:
print(x_train)

[[0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [9]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [10]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [11]:
print(y_test)

[0 1]


Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform
(x_train[:, 3:])
x_test[:, 3:] = sc.transform
(x_test[:, 3:])
print(x_train)
print(x_test)

[[0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 1.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [1.0 0.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [1.0 0.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 1.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound met